services:
  discovery-services:
    build: ./DiscoveryService
    container_name: discovery-services
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  config-services:
    build: ./Config-Service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:9999/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
    depends_on:
      discovery-services:
        condition: service_healthy

  client-service:
    build: ./Cliente-service
    container_name: client-service
    ports:
      - '8084:8084'
    expose:
      - '8084'
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8084/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
      - CONFIG-SERVICE_URL=http://config-services:9999
    depends_on:
      config-services:
        condition: service_healthy

  produit-service:
    build: ./Produite-service
    container_name: produit-service
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
      - CONFIG-SERVICE_URL=http://config-services:9999
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8085/actuator/health" ]
    depends_on:
      client-service:
        condition: service_healthy

  vente-service:
    build: ./Venteee-service
    container_name: vente-service
    ports:
      - '8086:8086'
    expose:
      - '8086'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
      - CONFIG-SERVICE_URL=http://config-services:9999
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8086/actuator/health" ]
    depends_on:
      produit-service:
        condition: service_healthy
      client-service:
        condition: service_healthy

  gatway-service:
    build: ./Gateway-Service
    container_name: gatway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-services:8761/eureka
      - CONFIG-SERVICE_URL=http://config-services:9999
    depends_on:
      config-services:
        condition: service_healthy
  devise-service:
    build: ./Devise_MS2
    container_name: devise-service
    ports:
      - '8811:8811'  # Changement ici pour éviter conflit
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      produit-service:
        condition: service_healthy
      client-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8813/actuator/health"]
      interval: 10s
      retries: 4